Remove centos-8 build
Centos Stream 8 is end of line since May 31.
https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

And the container fail to build when downloading metadata:

    CentOS Stream 8 - AppStream                     212  B/s |  38  B     00:00
    Error: Failed to download metadata for repo 'appstream': Cannot
    prepare internal mirrorlist: No URLs in mirrorlist