Use distribution pytest and reuse
Installing `pytest` and `reuse` from pypi does not work when running the
tests during the build. Strangely both programs are found by meson:

    Program pytest found: YES (/usr/local/bin/pytest)
    Program reuse found: YES (/usr/local/bin/reuse)

but when trying to run them we fail with:

    3/4 blksum  FAIL            0.03s   exit status 1
    >>> HAVE_NBD=1 MALLOC_PERTURB_=227 BLKSUM_DEBUG=1
        BLKSUM=/builds/nirs/blkhash/build/rpm/BUILD/blkhash-0.1/redhat-linux-build/blksum
        /usr/local/bin/pytest
    ――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
    stderr:
    Traceback (most recent call last):
      File "/usr/local/bin/pytest", line 5, in <module>
        from pytest import console_main
    ModuleNotFoundError: No module named 'pytest'
    ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
    4/4 reuse   FAIL            0.03s   exit status 1
    >>> MALLOC_PERTURB_=131 /usr/local/bin/reuse lint
    ――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
    stderr:
    Traceback (most recent call last):
      File "/usr/local/bin/reuse", line 5, in <module>
        from reuse._main import main
    ModuleNotFoundError: No module named 'reuse'
    ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Installing the distro packages fixes this issue, and both tests succeed:

    3/4 blksum  OK             14.32s
    4/4 reuse   OK              0.43s

On Fedora 35 we have very recent versions of `pytest` and `reuse`, so we
can use the distro package.

On Centos Stream we have an older version of `pytest` and on Stream 8 it
is installed as `pytest-3`.

On Centos `reuse` is not packaged, so we cannot run the `reuse` test,
but this test is not needed on all distros.

We can require the `reuse` package during build, but `reuse lint`
depends on git, so we cannot run it during rpmbuild.