More strict pytest call
When calling pytest without a test module, it searches for tests in the
entire tree. Turns out that if we have something that looks like a
docstring test in the commit message, pytest will find it inside the
meson-logs directory and try to run the docstring test:

    blksum_test.py::test_default_digest PASSED                               [ 99%]
    redhat-linux-build/meson-logs/testlog.txt::testlog.txt FAILED            [100%]
    =================================== FAILURES ===================================
    ____________________________ [doctest] testlog.txt _____________________________
    006 tests during the build. Strangely both pytest and reuse program are
    007 found by meson:
    008
    009     Program pytest found: YES (/usr/local/bin/pytest)
    010     Program reuse found: YES (/usr/local/bin/reuse)
    011
    012 but when trying to run them we fail with:
    013
    014     3/4 blksum  FAIL            0.03s   exit status 1
    015     >>> HAVE_NBD=1 MALLOC_PERTURB_=227 BLKSUM_DEBUG=1
    UNEXPECTED EXCEPTION: SyntaxError('invalid syntax', ('<doctest
    testlog.txt[0]>', 1, 12, 'HAVE_NBD=1 MALLOC_PERTURB_=227
    BLKSUM_DEBUG=1\n', 1, 27))
    Traceback (most recent call last):
      File "/usr/lib64/python3.10/doctest.py", line 1346, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest testlog.txt[0]>", line 1
        HAVE_NBD=1 MALLOC_PERTURB_=227 BLKSUM_DEBUG=1
                   ^^^^^^^^^^^^^^^
    SyntaxError: invalid syntax

Specify the test file name to avoid this trouble. We could also skip the
build directory but we don't really need to search for tests in this
project.